(feat) add login feature
Ductuan92/carForRent pull request #1
Opened 2022-05-23 02:08 UTC by Ductuan92

add login feature.

2022-05-24 13:38 UTC, bangdinhnfq requested changes

2022-05-24 13:38 UTC, bangdinhnfq commented on .phpunit.result.cache
> +{"version":1,"defects":{"Warning":6,"Tests\\src\\request\\UserLoginRequestTest::testValidateEmptyUserNamePassword with data set \"happy-case 1\"":4,"Tests\\src\\Validation\\UserLoginValidateTest::tes
Please add this file to gitignore

2022-05-24 13:38 UTC, bangdinhnfq commented on composer.json
> +    "composer/xdebug-handler": "^3.0"
Should put this package to require-dev

2022-05-24 13:38 UTC, bangdinhnfq commented on src/App/Route.php
> +        if(empty($this->controllerClassName))
Please follow code standard https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2022-05-24 13:38 UTC, bangdinhnfq commented on src/App/Route.php
> +        if(empty($this->actionName))
Please follow code standard https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2022-05-24 13:38 UTC, bangdinhnfq commented on src/Controller/LoginController.php
> +        if ($user)
How about the case user is empty?

2022-05-24 13:38 UTC, bangdinhnfq commented on src/Validation/UserLoginVerify.php
> +        //$passwordHash = password_hash($passwordRequest, PASSWORD_DEFAULT);
Please remove unused code

2022-05-24 13:38 UTC, bangdinhnfq commented on src/Validation/UserLoginVerify.php
> +        else
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2022-05-24 13:38 UTC, bangdinhnfq commented on src/Validation/UserRequestValidation.php
> +        if(empty($userRequest->getUserName()) || empty($userRequest->getPassword()))
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2022-06-09 02:09 UTC, closed without merging

2022-06-09 02:09 UTC, Ductuan92 commented
code already merge to master